/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import server.Server;

/**
 *
 * @author student
 */
public class ServerskaForma extends javax.swing.JFrame {
     Server server ;
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
         server = new Server();
        jLabelStatus.setText("");
        jButtonZAUSTAVI.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonZAUSTAVI = new javax.swing.JButton();
        jButtonPOKRENI = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonZAUSTAVI.setText("ZAUSTAVI");
        jButtonZAUSTAVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZAUSTAVIActionPerformed(evt);
            }
        });

        jButtonPOKRENI.setText("POKRENI");
        jButtonPOKRENI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPOKRENIActionPerformed(evt);
            }
        });

        jLabel1.setText("Status servera:");

        jLabelStatus.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonZAUSTAVI)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonPOKRENI))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(jLabelStatus)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelStatus))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZAUSTAVI)
                    .addComponent(jButtonPOKRENI))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZAUSTAVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZAUSTAVIActionPerformed
          server.zaustaviServer();
        jLabelStatus.setText("ZAUSTAVLJEN");
        jButtonPOKRENI.setEnabled(true);
        jButtonZAUSTAVI.setEnabled(false);
    }//GEN-LAST:event_jButtonZAUSTAVIActionPerformed

    private void jButtonPOKRENIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPOKRENIActionPerformed
        server.start();
        jLabelStatus.setText("POKRENUT");
        jButtonZAUSTAVI.setEnabled(true);
        jButtonPOKRENI.setEnabled(false);
    }//GEN-LAST:event_jButtonPOKRENIActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPOKRENI;
    private javax.swing.JButton jButtonZAUSTAVI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStatus;
    // End of variables declaration//GEN-END:variables
}
